### ISSUE TITLE
Open error occurs when catkin_make

### ISSUE THREAD

**Issue by skylook** [severin-lemaignan/ros-facetracking#2] opened 2015-10-26 06:24 UTC
/usr/include/opencv2/contrib/openfabmap.hpp:352:5: error: ‘vector’ does not name a type
     vector<Mat> imgDescriptors;
     ^
/usr/include/opencv2/contrib/openfabmap.hpp:378:5: error: ‘vector’ does not name a type
     vector<int> extractChildren(list<info> &remaining_edges, int q);
     ^
make[2]: **\* [ros-facetracking/CMakeFiles/facetracking.dir/src/human.cpp.o] Error 1
make[2]: **\* Waiting for unfinished jobs....
make[2]: **\* [ros-facetracking/CMakeFiles/facetracking.dir/src/recognition.cpp.o] Error 1
make[2]: **\* [ros-facetracking/CMakeFiles/facetracking.dir/src/facetracking.cpp.o] Error 1
make[1]: **\* [ros-facetracking/CMakeFiles/facetracking.dir/all] Error 2
make: **\* [all] Error 2
Invoking "make -j4 -l4" failed

**Comment by severin-lemaignan** [comment] 2015-10-29 10:29
@skylook Hello and thanks for your bug report.

Apparently, the issue is with your installation of `opencv`: you may have an out-of-date clone of `openfabmap` (I don't know this opencv module).

Since the bug seems unrelated to `ros-facetracking`, I close it. Feel free to re-open if needed!

**Closed as completed by severin-lemaignan** 2015-10-29 10:29 UTC
